### ISSUE TITLE
this.onUpdate is not a function

### ISSUE THREAD

**Issue by alexdrans** [BioPhoton/angular1-star-rating#44]
Using the directive with the following options; 

```<star-rating-comp rating="3" on-update="vm.yo()"></star-rating-comp>```

causes the error `` this.onUpdate is not a function`` to fire when it hits [this line](https://github.com/BioPhoton/angular1-star-rating/blob/master/src/star-rating.controller.ts#L220). Same happens without the on-update property. 

Any ideas..? 

ps nice repo

**Comment by BioPhoton** [comment]
Hi @alexdrans!

I will check this asap! I'm back from hollydays at the end of next week. 

If you have time you could try to find a solution in the meantime and pr it. 😉
Otherwise I will fix it in a week. 😀

**Comment by BioPhoton** [comment]
I could not reproduce the bug.

What i did was:
- [x] refactored handling of all custom callback
- [x] implemented function spy's for all nearly all functions call in this component
- [x] updated example
- [x] created plunker of example
- [x] released new version on npm

Let me know if this was helpful.

**Comment by Lennaert** [comment]
Hi!

I actually have a similar issue.
Maybe it's because I'm using it in combination with gulp-inject / main-bower-files.

Anyhow, as soon as I include the package (through Bower), a new warning turns up:
`WARNING: Tried to load angular more than once.`

Then, just like Alex, I'm getting an error after the page has loaded:
```
this.onRatingUpdate is not a function
```

Some parameters:
- Angular 1.5.8
- Installed with Bower (angular1-star-rating version 1.2.5)
- Using Gulp-Inject
- New error "WARNING: Tried to load angular more than once."
- Angular seed generated from Yeoman (generator-gulp-angular)

**Comment by BioPhoton** [comment]
Hi @Lennaert.

Will take a look asap!

Could you please post informations about the browser? 

Thx

**Comment by Lennaert** [comment]
Hi!
It's Chrome 55 on MacOSX.
Don't ASAP, take your time :-)

**Comment by BioPhoton** [comment]
I have created a new issue for the "Tried to load angular more than once." warning here => #51

**Comment by BioPhoton** [comment]
hi @Lennaert, 

could you do me a favor and test the new dist files from branch [15-ng_load_more_than_once](https://github.com/BioPhoton/angular1-star-rating/tree/%2315-ng_load_more_than_once) and answer in issue #51?

thx

**Comment by Viveur** [comment]
Hey, am also experiencing the same issue...

`v1.2.4: this.onUpdate is not a function`

`master: this.onRatingUpdate is not a function`

Switched over to the 15-ng_load_more_than_once branch and now seeing the same error Lennaert mentioned in #51 

`Uncaught ReferenceError: require is not defined`

**Comment by BioPhoton** [comment]
Hi @TheCopartnery.
Thx for your comment!
It seems like i have some wrong settings in my build process... Any input from your side?

**Comment by ioanabote** [comment]
Having the same issue when using
 `<star-rating-comp ... on-rating-change="onRatingChange()"></star-rating-comp>`
Error is:
 `TypeError: this.onRatingChange is not a function`

**Comment by Viveur** [comment]
Hey. Just had a chance to test this with v1.2.7 and am sorry to report that I'm still getting the same onRatingChange error.

**Comment by BioPhoton** [comment]
Should be working in 1.2.9

**Comment by Lennaert** [comment]
This is awesome @BioPhoton It's working great now, thank you for all your efforts!
